"""赛事生命周期、并发场次和动作截止时间编排。"""

from hangma_bot.application.contracts import (
    ActionAttempt,
    AuditContext,
    AuditKind,
    AuditRecord,
    AuditReceipt,
    AuditSummary,
    GameFailed,
    GameFinished,
    GameSessionPort,
    ObservedActionWindow,
    ParticipantTerminal,
    ParticipantTerminalReason,
    ReadyResult,
    RegistrationResult,
    RuntimeMode,
    RuntimeTarget,
    SessionBootstrap,
    StageIdentity,
    SubmitAccepted,
    SubmitAmbiguous,
    SubmitFatal,
    SubmitNotSent,
    SubmitOutcome,
    SubmitRejectedClosed,
    SubmitRejectedNoRefresh,
    SubmitRejectedRetryable,
    TournamentSessionPort,
    TournamentSnapshot,
    TournamentStatus,
)
from hangma_bot.application.auto_match_runtime import AutoMatchRuntime, AutoMatchSettings
from hangma_bot.application.deadline import BudgetPolicy, BoundedBackoff, SystemClock
from hangma_bot.application.participant_runtime import ParticipantRuntime
from hangma_bot.application.tournament_supervisor import SupervisionPolicy

__all__ = [
    "ActionAttempt",
    "AuditContext",
    "AutoMatchRuntime",
    "AutoMatchSettings",
    "AuditKind",
    "AuditRecord",
    "AuditReceipt",
    "AuditSummary",
    "BudgetPolicy",
    "BoundedBackoff",
    "GameFailed",
    "GameFinished",
    "GameSessionPort",
    "ObservedActionWindow",
    "ParticipantRuntime",
    "ParticipantTerminal",
    "ParticipantTerminalReason",
    "ReadyResult",
    "RegistrationResult",
    "RuntimeMode",
    "RuntimeTarget",
    "SessionBootstrap",
    "StageIdentity",
    "SubmitAccepted",
    "SubmitAmbiguous",
    "SubmitFatal",
    "SubmitNotSent",
    "SubmitOutcome",
    "SubmitRejectedClosed",
    "SubmitRejectedNoRefresh",
    "SubmitRejectedRetryable",
    "SupervisionPolicy",
    "SystemClock",
    "TournamentSessionPort",
    "TournamentSnapshot",
    "TournamentStatus",
]
