"""R18 累计正向能力候选的冻结源码身份；仅供离线研究注册。"""

R18_INTEGRATED_POSITIVE_V1_NAME = "r18_integrated_positive_v1"
R18_INTEGRATED_POSITIVE_V1_SHA256 = "0d3c094d9ee5f5fd0316d0c3db7563523ce1d8d2fafb0e64d3d9b93817909b2d"
R18_INTEGRATED_POSITIVE_V1_SOURCE = (
    '"""R18 多财神飘、补杠支配、庄家起手七对与双财神保包头覆盖；稳定 V2 是完整回退。"""\n'
    '\n'
    'def score_actions(view):\n'
    '    """按同一动作窗口的只读可见事实，为全部合法动作评分。"""\n'
    '    actions = view.get("actions")\n'
    '    visible = view.get("visible_state")\n'
    '    if actions is None or visible is None or len(actions) == 0:\n'
    '        return {"status": "ABSTAIN", "reason": "缺少动作表或公开可见状态"}\n'
    '    seat = visible.get("seat")\n'
    '    if seat is None or seat is True or seat is False or seat < 0 or seat > 3:\n'
    '        return {"status": "ABSTAIN", "reason": "我方座位不可用"}\n'
    '    hand = visible.get("my_hand")\n'
    '    discards = visible.get("discards")\n'
    '    melds = visible.get("melds")\n'
    '    scores = visible.get("table_scores")\n'
    '    rule_state = visible.get("rule_state")\n'
    '    if hand is None or discards is None or melds is None or scores is None or rule_state is None:\n'
    '        return {"status": "ABSTAIN", "reason": "基础公式所需公开状态缺失"}\n'
    '    if len(discards) != 4 or len(melds) != 4 or len(scores) != 4:\n'
    '        return {"status": "ABSTAIN", "reason": "四座公开状态长度不合法"}\n'
    '    wealth = rule_state.get("wealth_god")\n'
    '    if wealth is None:\n'
    '        return {"status": "ABSTAIN", "reason": "财神牌码缺失"}\n'
    '    own_meld_count = len(melds[seat])\n'
    '    wealth_count = hand.count(wealth)\n'
    '    drawn = visible.get("drawn_tile")\n'
    '    if drawn is not None and len(hand) != 14 - 3 * own_meld_count and drawn == wealth:\n'
    '        wealth_count += 1\n'
    '    own_table_score = scores[seat]\n'
    '    if own_table_score is None or own_table_score is True or own_table_score is False:\n'
    '        return {"status": "ABSTAIN", "reason": "我方桌内积分缺失"}\n'
    '    own_table_value = float(own_table_score)\n'
    '    if own_table_value - own_table_value != 0:\n'
    '        return {"status": "ABSTAIN", "reason": "我方桌内积分非有限"}\n'
    '    table_rank = 1\n'
    '    for item in scores:\n'
    '        if item is None or item is True or item is False:\n'
    '            return {"status": "ABSTAIN", "reason": "桌内积分缺失"}\n'
    '        value = float(item)\n'
    '        if value - value != 0:\n'
    '            return {"status": "ABSTAIN", "reason": "桌内积分非有限"}\n'
    '        if value > own_table_value:\n'
    '            table_rank += 1\n'
    '    dealer = visible.get("dealer_seat")\n'
    '    if dealer is None or dealer is True or dealer is False or dealer < 0 or dealer > 3:\n'
    '        return {"status": "ABSTAIN", "reason": "庄家座位不可用"}\n'
    '    pending = []\n'
    '    known = []\n'
    '    best_shanten = None\n'
    '    for action in actions:\n'
    '        key = action.get("action_key")\n'
    '        kind = action.get("action_type")\n'
    '        if key is None or kind is None or action.get("is_legal") is not True:\n'
    '            return {"status": "ABSTAIN", "reason": "动作合法身份或键缺失"}\n'
    '        direct = False\n'
    '        base = None\n'
    '        shanten = action.get("shanten_after")\n'
    '        useful = action.get("useful_tiles")\n'
    '        if kind == "hu":\n'
    '            direct = True\n'
    '            base = 1000.0\n'
    '            if best_shanten is None or -1 < best_shanten:\n'
    '                best_shanten = -1\n'
    '        elif action.get("fact_kind") == "hand_progress" and shanten is not None and shanten is not True and shanten is not False and shanten >= 0:\n'
    '            valid_useful = True\n'
    '            support = 0.0\n'
    '            for tile in useful:\n'
    '                remaining = tile.get("remaining_estimate")\n'
    '                if remaining is None or remaining is True or remaining is False:\n'
    '                    valid_useful = False\n'
    '                else:\n'
    '                    amount = float(remaining)\n'
    '                    if amount - amount != 0:\n'
    '                        valid_useful = False\n'
    '                    else:\n'
    '                        support += amount\n'
    '            if valid_useful:\n'
    '                direct = True\n'
    '                base = -100.0 * float(shanten) + round(support, 1)\n'
    '                if kind != "pass" and (best_shanten is None or shanten < best_shanten):\n'
    '                    best_shanten = shanten\n'
    '        if kind == "pass" and direct:\n'
    '            if action.get("best_followup_discard") is not None or action.get("replacement_draw_unknown") is not False:\n'
    '                direct = False\n'
    '                base = None\n'
    '        produced = action.get("immediate_settlement") is not None\n'
    '        routes = action.get("routes")\n'
    '        branches = action.get("followup_branches")\n'
    '        families = action.get("family_progress_entries")\n'
    '        if routes is not None and len(routes) > 0:\n'
    '            produced = True\n'
    '        if branches is not None:\n'
    '            produced = True\n'
    '        if families is not None and len(families) > 0:\n'
    '            produced = True\n'
    '        if direct:\n'
    '            pending.append({"action": action, "base": base, "basis": "direct_v2", "shanten": shanten})\n'
    '            known.append(base)\n'
    '        elif produced:\n'
    '            pending.append({"action": action, "base": 0.0, "basis": "produced_outside_v2", "shanten": None})\n'
    '            known.append(0.0)\n'
    '        else:\n'
    '            pending.append({"action": action, "base": None, "basis": "unknown", "shanten": None})\n'
    '    if len(known) == 0:\n'
    '        return {"status": "ABSTAIN", "reason": "全部动作均无已生产事实，未知不能取零分"}\n'
    '    base_floor = min(known)\n'
    '    entries = []\n'
    '    for item in pending:\n'
    '        action = item.get("action")\n'
    '        key = action.get("action_key")\n'
    '        kind = action.get("action_type")\n'
    '        base = item.get("base")\n'
    '        unknown = base is None\n'
    '        total = base_floor - 1.0 if unknown else base\n'
    '        retained_wealth = wealth_count\n'
    '        tile_code = None\n'
    '        if kind == "discard":\n'
    '            tile_code = key[8:]\n'
    '            if tile_code == wealth:\n'
    '                retained_wealth -= 1\n'
    '        wealth_part = 5.0 * retained_wealth\n'
    '        total += wealth_part\n'
    '        wealth_discard_part = 0.0\n'
    '        river_part = 0.0\n'
    '        risk_units = 0.0\n'
    '        style_part = 0.0\n'
    '        familiar = False\n'
    '        if kind == "discard":\n'
    '            if tile_code == wealth:\n'
    '                wealth_discard_part = -60.0\n'
    '                total += wealth_discard_part\n'
    '            for river_seat in range(4):\n'
    '                if river_seat != seat and discards[river_seat].count(tile_code) > 0:\n'
    '                    familiar = True\n'
    '            if familiar:\n'
    '                river_part = 3.0\n'
    '                total += river_part\n'
    '            elif len(tile_code) >= 2 and tile_code[0] in "123456789" and tile_code[-1] in "wbt":\n'
    '                suit = tile_code[-1]\n'
    '                rank = int(tile_code[0])\n'
    '                next_seat = (seat + 1) % 4\n'
    '                near_next = False\n'
    '                near_dealer = False\n'
    '                for meld in melds[next_seat]:\n'
    '                    for other in meld.get("tiles"):\n'
    '                        if len(other) >= 2 and other[0] in "123456789" and other[-1] == suit and abs(int(other[0]) - rank) <= 2:\n'
    '                            near_next = True\n'
    '                if dealer != seat:\n'
    '                    for meld in melds[dealer]:\n'
    '                        for other in meld.get("tiles"):\n'
    '                            if len(other) >= 2 and other[0] in "123456789" and other[-1] == suit and abs(int(other[0]) - rank) <= 2:\n'
    '                                near_dealer = True\n'
    '                if near_next:\n'
    '                    risk_units += 1.0\n'
    '                if near_dealer:\n'
    '                    risk_units += 0.5\n'
    '                total -= round(6.0 * risk_units, 1)\n'
    '            if table_rank == 1 and familiar:\n'
    '                style_part = 4.0\n'
    '            elif table_rank == 4 and item.get("shanten") is not None and item.get("shanten") == best_shanten:\n'
    '                style_part = 2.0\n'
    '            total = round(total, 6)\n'
    '            total += style_part\n'
    '            total = round(total, 6)\n'
    '        else:\n'
    '            fixed = 0.0\n'
    '            if kind == "peng":\n'
    '                fixed = -6.0\n'
    '            elif kind == "chi":\n'
    '                fixed = -10.0\n'
    '            elif kind == "gang":\n'
    '                fixed = 40.0\n'
    '            total += fixed\n'
    '            total = round(total, 6)\n'
    '        trace = {"basis": item.get("basis"), "base_score": base, "shanten_after": item.get("shanten"), "best_shanten_non_pass": best_shanten, "wealth_part": wealth_part, "wealth_discard_part": wealth_discard_part, "river_part": river_part, "risk_units": risk_units, "style_part": style_part, "unknown": unknown, "unknown_policy": "known_final_floor_minus_1" if unknown else None, "hu_sorting_layer": kind == "hu", "scope": "direct_v2_or_produced_outside_v2"}\n'
    '        entries.append({"action_key": key, "action_type": kind, "score": total, "trace": trace})\n'
    '    hu_level = None\n'
    '    for entry in entries:\n'
    '        if entry.get("trace").get("unknown") is not True and entry.get("action_type") != "hu":\n'
    '            score = entry.get("score")\n'
    '            if hu_level is None or score > hu_level:\n'
    '                hu_level = score\n'
    '    known_floor = None\n'
    '    for entry in entries:\n'
    '        if entry.get("trace").get("unknown") is not True:\n'
    '            score = entry.get("score")\n'
    '            if entry.get("action_type") == "hu" and hu_level is not None:\n'
    '                score = hu_level + 1.0\n'
    '            if known_floor is None or score < known_floor:\n'
    '                known_floor = score\n'
    '    if known_floor is None:\n'
    '        return {"status": "ABSTAIN", "reason": "没有可用已知最终评分，未知不能取零分"}\n'
    '    if wealth_count == 4:\n'
    '        overlay_name = "four_wealth_piao_proxy_boundary/v1"\n'
    '        overlay_required_ratio = 1.50\n'
    '    elif wealth_count == 3:\n'
    '        overlay_name = "three_wealth_piao_cf_supported/v1"\n'
    '        overlay_required_ratio = 1.75\n'
    '    else:\n'
    '        overlay_name = None\n'
    '        overlay_required_ratio = None\n'
    '    overlay_best_key = None\n'
    '    overlay_best_proxy = None\n'
    '    overlay_immediate_hu = None\n'
    '    overlay_actual_ratio = None\n'
    '    overlay_triggered = False\n'
    '    overlay_degrade_reason = "目标机会窗口不成立"\n'
    '    overlay_unknown_pool = None\n'
    '    if overlay_name is not None and rule_state.get("baotou") is True and hu_level is not None:\n'
    '        overlay_degrade_reason = "立即胡结算事实不完整"\n'
    '        for action in actions:\n'
    '            if action.get("is_legal") is True and action.get("action_type") == "hu":\n'
    '                settlement = action.get("immediate_settlement")\n'
    '                if settlement is not None:\n'
    '                    delta = settlement.get("score_delta")\n'
    '                    if delta is not None and len(delta) == 4:\n'
    '                        amount = delta[seat]\n'
    '                        if amount is not None and amount is not True and amount is not False:\n'
    '                            value = float(amount)\n'
    '                            if value - value == 0 and value > 0.0:\n'
    '                                overlay_immediate_hu = value\n'
    '        remaining_count = visible.get("remaining_tile_count")\n'
    '        hand_counts = visible.get("hand_counts")\n'
    '        if remaining_count is not None and remaining_count is not True and remaining_count is not False and hand_counts is not None and len(hand_counts) == 4:\n'
    '            pool = float(remaining_count)\n'
    '            pool_ok = pool - pool == 0 and pool >= 0.0\n'
    '            for other_seat in range(4):\n'
    '                if other_seat != seat:\n'
    '                    count = hand_counts[other_seat]\n'
    '                    if count is None or count is True or count is False:\n'
    '                        pool_ok = False\n'
    '                    else:\n'
    '                        count_value = float(count)\n'
    '                        if count_value - count_value != 0 or count_value < 0.0:\n'
    '                            pool_ok = False\n'
    '                        else:\n'
    '                            pool += count_value\n'
    '            if pool_ok and pool > 0.0:\n'
    '                overlay_unknown_pool = pool\n'
    '        if overlay_immediate_hu is not None and overlay_unknown_pool is not None:\n'
    '            overlay_degrade_reason = "没有完整且满足家族转移的目标弃牌"\n'
    '            for action in actions:\n'
    '                key = action.get("action_key")\n'
    '                kind = action.get("action_type")\n'
    '                if kind != "discard" or key is None:\n'
    '                    continue\n'
    '                tile_code = key[8:]\n'
    '                target_shape = tile_code == wealth\n'
    '                family_ok = False\n'
    '                families = action.get("family_progress_entries")\n'
    '                if families is not None:\n'
    '                    for family in families:\n'
    '                        if family.get("family") == "chain" and family.get("route_status") == "witnessed" and family.get("progress") == "advance":\n'
    '                            family_ok = True\n'
    '                facts_ok = target_shape and family_ok\n'
    '                if action.get("value_coverage") != "complete":\n'
    '                    facts_ok = False\n'
    '                issues = action.get("value_issues")\n'
    '                if issues is None or len(issues) != 0:\n'
    '                    facts_ok = False\n'
    '                routes = action.get("routes")\n'
    '                if routes is None or len(routes) == 0:\n'
    '                    facts_ok = False\n'
    '                numerator = 0.0\n'
    '                seen_codes = []\n'
    '                if facts_ok:\n'
    '                    for route in routes:\n'
    '                        route_ok = route.get("followup_discard") is None\n'
    '                        route_shanten = route.get("shanten")\n'
    '                        if route_shanten is None or route_shanten is True or route_shanten is False or route_shanten != 0:\n'
    '                            route_ok = False\n'
    '                        if route.get("support") != "conditional_witness":\n'
    '                            route_ok = False\n'
    '                        conditional = route.get("conditional_settlement")\n'
    '                        route_value = None\n'
    '                        if conditional is not None:\n'
    '                            route_delta = conditional.get("score_delta")\n'
    '                            if route_delta is not None and len(route_delta) == 4:\n'
    '                                route_amount = route_delta[seat]\n'
    '                                if route_amount is not None and route_amount is not True and route_amount is not False:\n'
    '                                    converted = float(route_amount)\n'
    '                                    if converted - converted == 0 and converted >= 0.0:\n'
    '                                        route_value = converted\n'
    '                        if route_value is None:\n'
    '                            route_ok = False\n'
    '                        useful_tiles = route.get("useful_tiles")\n'
    '                        if useful_tiles is None or len(useful_tiles) == 0:\n'
    '                            route_ok = False\n'
    '                        if route_ok:\n'
    '                            for useful in useful_tiles:\n'
    '                                code = useful.get("code")\n'
    '                                estimate = useful.get("remaining_estimate")\n'
    '                                if code is None or code in seen_codes or estimate is None or estimate is True or estimate is False:\n'
    '                                    route_ok = False\n'
    '                                else:\n'
    '                                    estimate_value = float(estimate)\n'
    '                                    if estimate_value - estimate_value != 0 or estimate_value < 0.0 or estimate_value > 4.0:\n'
    '                                        route_ok = False\n'
    '                                    else:\n'
    '                                        seen_codes.append(code)\n'
    '                                        numerator += route_value * estimate_value\n'
    '                        if not route_ok:\n'
    '                            facts_ok = False\n'
    '                            break\n'
    '                if facts_ok:\n'
    '                    proxy = numerator / overlay_unknown_pool\n'
    '                    if overlay_best_proxy is None or proxy > overlay_best_proxy or (proxy == overlay_best_proxy and key < overlay_best_key):\n'
    '                        overlay_best_proxy = proxy\n'
    '                        overlay_best_key = key\n'
    '            if overlay_best_proxy is not None:\n'
    '                overlay_actual_ratio = overlay_best_proxy / overlay_immediate_hu\n'
    '                overlay_degrade_reason = "条件代理优势未达到预登记风险缓冲"\n'
    '                if overlay_actual_ratio >= overlay_required_ratio:\n'
    '                    overlay_triggered = True\n'
    '                    overlay_degrade_reason = "触发"\n'
    '    canonical_codes = (\n'
    '        "1w", "2w", "3w", "4w", "5w", "6w", "7w", "8w", "9w",\n'
    '        "1b", "2b", "3b", "4b", "5b", "6b", "7b", "8b", "9b",\n'
    '        "1t", "2t", "3t", "4t", "5t", "6t", "7t", "8t", "9t",\n'
    '        "东", "南", "西", "北", "中", "发", "白",\n'
    '    )\n'
    '    dominance_hu_value = None\n'
    '    for action in actions:\n'
    '        if action.get("is_legal") is True and action.get("action_type") == "hu":\n'
    '            settlement = action.get("immediate_settlement")\n'
    '            if settlement is not None:\n'
    '                delta = settlement.get("score_delta")\n'
    '                if delta is not None and len(delta) == 4:\n'
    '                    amount = delta[seat]\n'
    '                    if amount is not None and amount is not True and amount is not False:\n'
    '                        value = float(amount)\n'
    '                        if value - value == 0:\n'
    '                            dominance_hu_value = value\n'
    '    dominance_best_key = None\n'
    '    dominance_best_value = None\n'
    '    dominance_checks = None\n'
    '    if dominance_hu_value is not None:\n'
    '        for action in actions:\n'
    '            key = action.get("action_key")\n'
    '            added_gang = action.get("action_type") == "gang" and key is not None and key[:11] == "gang:added:"\n'
    '            coverage_complete = action.get("value_coverage") == "complete"\n'
    '            no_value_issues = action.get("value_issues") is not None and len(action.get("value_issues")) == 0\n'
    '            replacement_unknown = action.get("replacement_draw_unknown") is True\n'
    '            standard_shanten_zero = action.get("standard_shanten_after") is not True and action.get("standard_shanten_after") is not False and action.get("standard_shanten_after") == 0\n'
    '            standard = action.get("standard_useful_tiles")\n'
    '            standard_seen = []\n'
    '            publicly_possible = []\n'
    '            standard_ok = standard is not None and len(standard) == len(canonical_codes)\n'
    '            if standard_ok:\n'
    '                for useful in standard:\n'
    '                    code = useful.get("code")\n'
    '                    estimate = useful.get("remaining_estimate")\n'
    '                    if code not in canonical_codes or code in standard_seen or estimate is None or estimate is True or estimate is False:\n'
    '                        standard_ok = False\n'
    '                    else:\n'
    '                        remaining = float(estimate)\n'
    '                        if remaining - remaining != 0 or remaining < 0.0 or remaining > 4.0:\n'
    '                            standard_ok = False\n'
    '                        else:\n'
    '                            standard_seen.append(code)\n'
    '                            if remaining > 0.0:\n'
    '                                publicly_possible.append(code)\n'
    '            standard_codes_all_34 = standard_ok and len(standard_seen) == len(canonical_codes)\n'
    '            routes = action.get("routes")\n'
    '            route = None\n'
    '            if routes is not None and len(routes) == 1:\n'
    '                route = routes[0]\n'
    '            unique_route = route is not None\n'
    '            conditions = None if route is None else route.get("conditions")\n'
    '            replacement_route = conditions is not None and conditions.get("draw_kind") == "replacement"\n'
    '            route_shanten = None if route is None else route.get("shanten")\n'
    '            route_shanten_zero = route_shanten is not True and route_shanten is not False and route_shanten == 0\n'
    '            route_no_followup_discard = route is not None and route.get("followup_discard") is None\n'
    '            route_seen = []\n'
    '            route_ok = route is not None and route.get("useful_tiles") is not None and len(route.get("useful_tiles")) > 0\n'
    '            if route_ok:\n'
    '                for useful in route.get("useful_tiles"):\n'
    '                    code = useful.get("code")\n'
    '                    estimate = useful.get("remaining_estimate")\n'
    '                    if code not in canonical_codes or code in route_seen or estimate is None or estimate is True or estimate is False:\n'
    '                        route_ok = False\n'
    '                    else:\n'
    '                        remaining = float(estimate)\n'
    '                        if remaining - remaining != 0 or remaining <= 0.0 or remaining > 4.0:\n'
    '                            route_ok = False\n'
    '                        else:\n'
    '                            route_seen.append(code)\n'
    '            route_covers_publicly_possible = route_ok and sorted(route_seen) == sorted(publicly_possible)\n'
    '            route_value = None\n'
    '            conditional = None if route is None else route.get("conditional_settlement")\n'
    '            if conditional is not None:\n'
    '                delta = conditional.get("score_delta")\n'
    '                if delta is not None and len(delta) == 4:\n'
    '                    amount = delta[seat]\n'
    '                    if amount is not None and amount is not True and amount is not False:\n'
    '                        value = float(amount)\n'
    '                        if value - value == 0:\n'
    '                            route_value = value\n'
    '            route_score_strictly_higher = route_value is not None and route_value > dominance_hu_value\n'
    '            checks = {\n'
    '                "added_gang": added_gang,\n'
    '                "coverage_complete": coverage_complete,\n'
    '                "no_value_issues": no_value_issues,\n'
    '                "replacement_unknown": replacement_unknown,\n'
    '                "standard_shanten_zero": standard_shanten_zero,\n'
    '                "standard_codes_all_34": standard_codes_all_34,\n'
    '                "unique_route": unique_route,\n'
    '                "replacement_route": replacement_route,\n'
    '                "route_shanten_zero": route_shanten_zero,\n'
    '                "route_no_followup_discard": route_no_followup_discard,\n'
    '                "route_covers_publicly_possible": route_covers_publicly_possible,\n'
    '                "route_score_strictly_higher": route_score_strictly_higher,\n'
    '            }\n'
    '            predicate = True\n'
    '            for passed in checks.values():\n'
    '                if passed is not True:\n'
    '                    predicate = False\n'
    '            if predicate and (dominance_best_value is None or route_value > dominance_best_value or (route_value == dominance_best_value and key < dominance_best_key)):\n'
    '                dominance_best_key = key\n'
    '                dominance_best_value = route_value\n'
    '                dominance_checks = checks\n'
    '    final_entries = []\n'
    '    for entry in entries:\n'
    '        score = entry.get("score")\n'
    '        if entry.get("action_type") == "hu" and hu_level is not None:\n'
    '            score = hu_level + 1.0\n'
    '        if entry.get("trace").get("unknown") is True:\n'
    '            score = known_floor - 1.0\n'
    '        v2_score = score\n'
    '        if overlay_triggered and entry.get("action_key") == overlay_best_key:\n'
    '            score = hu_level + 2.0\n'
    '        before_dominance_score = score\n'
    '        if dominance_best_key is not None and entry.get("action_key") == dominance_best_key:\n'
    '            score = hu_level + 1.5\n'
    '        trace = entry.get("trace")\n'
    '        if overlay_best_key is not None and entry.get("action_key") == overlay_best_key:\n'
    '            trace = {"basis": trace.get("basis"), "base_score": trace.get("base_score"), "shanten_after": trace.get("shanten_after"), "best_shanten_non_pass": trace.get("best_shanten_non_pass"), "wealth_part": trace.get("wealth_part"), "wealth_discard_part": trace.get("wealth_discard_part"), "river_part": trace.get("river_part"), "risk_units": trace.get("risk_units"), "style_part": trace.get("style_part"), "unknown": trace.get("unknown"), "unknown_policy": trace.get("unknown_policy"), "hu_sorting_layer": trace.get("hu_sorting_layer"), "scope": trace.get("scope"), "r18_opportunity_overlay": {"structure": overlay_name, "triggered": overlay_triggered, "wealth_count": wealth_count, "immediate_hu_value": overlay_immediate_hu, "continue_proxy": overlay_best_proxy, "proxy_unknown_pool": overlay_unknown_pool, "required_ratio": overlay_required_ratio, "actual_ratio": overlay_actual_ratio, "score_delta": score - v2_score, "degrade_reason": overlay_degrade_reason, "limitation": "仅下一次本人自摸立即胡的条件代理，不是完整牌局期望；未建模他家先胡、鸣牌和轮转生存"}}\n'
    '        if dominance_best_key is not None and entry.get("action_key") == dominance_best_key:\n'
    '            trace = {"basis": trace.get("basis"), "base_score": trace.get("base_score"), "shanten_after": trace.get("shanten_after"), "best_shanten_non_pass": trace.get("best_shanten_non_pass"), "wealth_part": trace.get("wealth_part"), "wealth_discard_part": trace.get("wealth_discard_part"), "river_part": trace.get("river_part"), "risk_units": trace.get("risk_units"), "style_part": trace.get("style_part"), "unknown": trace.get("unknown"), "unknown_policy": trace.get("unknown_policy"), "hu_sorting_layer": trace.get("hu_sorting_layer"), "scope": trace.get("scope"), "r18_gang_dominance_overlay": {"structure": "added_gang_all_draws_strictly_dominate_hu/v1", "triggered": True, "hu_focal_score": dominance_hu_value, "gang_route_focal_score": dominance_best_value, "local_gain": dominance_best_value - dominance_hu_value, "checks": dominance_checks, "score_delta": score - before_dominance_score, "fallback": "任一事实缺失或判据失败时逐点评分保持P3"}}\n'
    '        final_entries.append({"action_key": entry.get("action_key"), "score": score, "trace": trace})\n'
    '    seven_value_best_key = None\n'
    '    seven_value_parent_key = None\n'
    '    seven_value_best_numerator = None\n'
    '    seven_value_parent_numerator = None\n'
    '    seven_value_denominator = None\n'
    '    seven_value_triggered = False\n'
    '    seven_value_degrade_reason = "未进入已验证的庄家起手首次摸牌域"\n'
    '    initial_hand_counts = visible.get("hand_counts")\n'
    '    initial_remaining_count = visible.get("remaining_tile_count")\n'
    '    initial_rivers_empty = True\n'
    '    for river in discards:\n'
    '        if len(river) != 0:\n'
    '            initial_rivers_empty = False\n'
    '    initial_melds_empty = True\n'
    '    for public_melds in melds:\n'
    '        if len(public_melds) != 0:\n'
    '            initial_melds_empty = False\n'
    '    validated_initial_domain = (\n'
    '        seat == dealer\n'
    '        and drawn is not None\n'
    '        and len(hand) == 13\n'
    '        and initial_remaining_count == 83\n'
    '        and initial_hand_counts is not None\n'
    '        and len(initial_hand_counts) == 4\n'
    '        and initial_hand_counts[seat] == 14\n'
    '        and initial_rivers_empty\n'
    '        and initial_melds_empty\n'
    '    )\n'
    '    pure_closed_discard = (\n'
    '        validated_initial_domain and len(actions) >= 2 and own_meld_count == 0\n'
    '    )\n'
    '    if pure_closed_discard:\n'
    '        for action in actions:\n'
    '            if action.get("is_legal") is not True or action.get("action_type") != "discard":\n'
    '                pure_closed_discard = False\n'
    '    if pure_closed_discard:\n'
    '        seven_value_degrade_reason = "至少一个动作的完整一次自摸价值事实不可用"\n'
    '        route_rows = []\n'
    '        all_complete = True\n'
    '        for action in actions:\n'
    '            key = action.get("action_key")\n'
    '            routes = action.get("routes")\n'
    '            issues = action.get("value_issues")\n'
    '            valid = (\n'
    '                key is not None\n'
    '                and action.get("fact_kind") == "hand_progress"\n'
    '                and action.get("pattern_progress_note") is None\n'
    '                and action.get("seven_pairs_shanten_after") is not None\n'
    '                and action.get("value_coverage") == "complete"\n'
    '                and issues is not None\n'
    '                and len(issues) == 0\n'
    '                and routes is not None\n'
    '            )\n'
    '            numerator = 0.0\n'
    '            seen_codes = []\n'
    '            seven_route = False\n'
    '            if valid:\n'
    '                for route in routes:\n'
    '                    route_valid = (\n'
    '                        route.get("followup_discard") is None\n'
    '                        and route.get("shanten") is not None\n'
    '                        and route.get("shanten") is not True\n'
    '                        and route.get("shanten") is not False\n'
    '                        and route.get("shanten") == 0\n'
    '                        and route.get("support") == "conditional_witness"\n'
    '                    )\n'
    '                    conditions = route.get("conditions")\n'
    '                    if conditions is None or conditions.get("draw_kind") != "normal":\n'
    '                        route_valid = False\n'
    '                    settlement = route.get("conditional_settlement")\n'
    '                    route_value = None\n'
    '                    details = None\n'
    '                    if settlement is not None:\n'
    '                        delta = settlement.get("score_delta")\n'
    '                        details = settlement.get("details")\n'
    '                        if delta is not None and len(delta) == 4:\n'
    '                            amount = delta[seat]\n'
    '                            if amount is not None and amount is not True and amount is not False:\n'
    '                                converted = float(amount)\n'
    '                                if converted - converted == 0 and converted >= 0.0:\n'
    '                                    route_value = converted\n'
    '                    if route_value is None or details is None:\n'
    '                        route_valid = False\n'
    '                    elif "七对" in details:\n'
    '                        seven_route = True\n'
    '                    useful_tiles = route.get("useful_tiles")\n'
    '                    if useful_tiles is None or len(useful_tiles) == 0:\n'
    '                        route_valid = False\n'
    '                    if route_valid:\n'
    '                        for useful in useful_tiles:\n'
    '                            code = useful.get("code")\n'
    '                            remaining = useful.get("remaining_estimate")\n'
    '                            if code not in canonical_codes or code in seen_codes or remaining is None or remaining is True or remaining is False:\n'
    '                                route_valid = False\n'
    '                            else:\n'
    '                                amount = float(remaining)\n'
    '                                if amount - amount != 0 or amount < 0.0 or amount > 4.0:\n'
    '                                    route_valid = False\n'
    '                                else:\n'
    '                                    seen_codes.append(code)\n'
    '                                    numerator += route_value * amount\n'
    '                    if not route_valid:\n'
    '                        valid = False\n'
    '                        break\n'
    '            if not valid:\n'
    '                all_complete = False\n'
    '            route_rows.append({"action_key": key, "numerator": numerator, "seven_route": seven_route})\n'
    '        if all_complete:\n'
    '            seven_value_parent_score = None\n'
    '            for entry in final_entries:\n'
    '                key = entry.get("action_key")\n'
    '                score = entry.get("score")\n'
    '                if seven_value_parent_score is None or score > seven_value_parent_score or (score == seven_value_parent_score and key < seven_value_parent_key):\n'
    '                    seven_value_parent_key = key\n'
    '                    seven_value_parent_score = score\n'
    '            for row in route_rows:\n'
    '                key = row.get("action_key")\n'
    '                numerator = row.get("numerator")\n'
    '                if key == seven_value_parent_key:\n'
    '                    seven_value_parent_numerator = numerator\n'
    '                if seven_value_best_numerator is None or numerator > seven_value_best_numerator or (numerator == seven_value_best_numerator and key < seven_value_best_key):\n'
    '                    seven_value_best_key = key\n'
    '                    seven_value_best_numerator = numerator\n'
    '            best_is_seven = False\n'
    '            for row in route_rows:\n'
    '                if row.get("action_key") == seven_value_best_key and row.get("seven_route") is True:\n'
    '                    best_is_seven = True\n'
    '            remaining_count = visible.get("remaining_tile_count")\n'
    '            hand_counts = visible.get("hand_counts")\n'
    '            if remaining_count is not None and remaining_count is not True and remaining_count is not False and hand_counts is not None and len(hand_counts) == 4:\n'
    '                denominator = float(remaining_count)\n'
    '                denominator_ok = denominator - denominator == 0 and denominator >= 0.0\n'
    '                for other_seat in range(4):\n'
    '                    if other_seat != seat:\n'
    '                        count = hand_counts[other_seat]\n'
    '                        if count is None or count is True or count is False:\n'
    '                            denominator_ok = False\n'
    '                        else:\n'
    '                            converted = float(count)\n'
    '                            if converted - converted != 0 or converted < 0.0:\n'
    '                                denominator_ok = False\n'
    '                            else:\n'
    '                                denominator += converted\n'
    '                if denominator_ok and denominator > 0.0:\n'
    '                    seven_value_denominator = denominator\n'
    '            seven_value_degrade_reason = "七对路线未严格提高完整一次自摸条件期望"\n'
    '            if best_is_seven and seven_value_denominator is not None and seven_value_best_numerator > seven_value_parent_numerator:\n'
    '                seven_value_triggered = True\n'
    '                seven_value_degrade_reason = "触发"\n'
    '                replaced_entries = []\n'
    '                for entry in final_entries:\n'
    '                    if entry.get("action_key") != seven_value_best_key:\n'
    '                        replaced_entries.append(entry)\n'
    '                    else:\n'
    '                        trace = entry.get("trace")\n'
    '                        score = seven_value_parent_score + 0.25\n'
    '                        trace = {"basis": trace.get("basis"), "base_score": trace.get("base_score"), "shanten_after": trace.get("shanten_after"), "best_shanten_non_pass": trace.get("best_shanten_non_pass"), "wealth_part": trace.get("wealth_part"), "wealth_discard_part": trace.get("wealth_discard_part"), "river_part": trace.get("river_part"), "risk_units": trace.get("risk_units"), "style_part": trace.get("style_part"), "unknown": trace.get("unknown"), "unknown_policy": trace.get("unknown_policy"), "hu_sorting_layer": trace.get("hu_sorting_layer"), "scope": trace.get("scope"), "r18_seven_pairs_value_overlay": {"structure": "dealer_initial_complete_one_self_draw_seven_pairs_value/v1", "triggered": True, "validated_domain": "庄家起手首次摸牌；83张公开余量；四家空牌河且无副露", "parent_action": seven_value_parent_key, "parent_expected_value": seven_value_parent_numerator / seven_value_denominator, "dominant_expected_value": seven_value_best_numerator / seven_value_denominator, "unknown_pool": seven_value_denominator, "score_delta": score - entry.get("score"), "degrade_reason": seven_value_degrade_reason, "fallback": "任一域边界、动作价值覆盖、路线合法性或七对严格价值优势不成立时逐点评分保持P5", "limitation": "只比较下一次本人摸牌立即胡的条件期望；已由16种起手×32完整世界续打校准，不向牌局中后段外推"}}\n'
    '                        replaced_entries.append({"action_key": seven_value_best_key, "score": score, "trace": trace})\n'
    '                final_entries = replaced_entries\n'
    '    # 双财神保包tou飘反事实覆盖：父代最终 entries 之上最小新增。\n'
    '    piao2_degrade_reason = "父代首选动作不是hu"\n'
    '    piao2_triggered = False\n'
    '    piao2_target_key = None\n'
    '    piao2_parent_top_action = None\n'
    '    piao2_hu_score = None\n'
    '    piao2_score_delta = 0.0\n'
    '    parent_top_entry = None\n'
    '    for entry in final_entries:\n'
    '        if parent_top_entry is None or entry.get("score") > parent_top_entry.get("score") or (entry.get("score") == parent_top_entry.get("score") and entry.get("action_key") < parent_top_entry.get("action_key")):\n'
    '            parent_top_entry = entry\n'
    '    if parent_top_entry is not None:\n'
    '        piao2_parent_top_action = parent_top_entry.get("action_key")\n'
    '        parent_top_type = None\n'
    '        for entry in entries:\n'
    '            if entry.get("action_key") == parent_top_entry.get("action_key") and parent_top_type is None:\n'
    '                parent_top_type = entry.get("action_type")\n'
    '        if parent_top_type == "hu":\n'
    '            piao2_degrade_reason = "准确财神数不等于2"\n'
    '            if wealth_count == 2:\n'
    '                piao2_degrade_reason = "合法动作中hu数量不唯一"\n'
    '                legal_hu_keys = []\n'
    '                legal_wealth_discards = []\n'
    '                for action in actions:\n'
    '                    if action.get("is_legal") is not True:\n'
    '                        continue\n'
    '                    key = action.get("action_key")\n'
    '                    kind = action.get("action_type")\n'
    '                    if kind == "hu" and key is not None:\n'
    '                        legal_hu_keys.append(key)\n'
    '                    if kind == "discard" and key is not None and key[8:] == wealth:\n'
    '                        legal_wealth_discards.append(action)\n'
    '                if len(legal_hu_keys) == 1:\n'
    '                    piao2_degrade_reason = "财神弃牌目标不唯一"\n'
    '                    if len(legal_wealth_discards) == 1:\n'
    '                        piao2_degrade_reason = "目标财神弃牌baotou_after非显式True"\n'
    '                        target = legal_wealth_discards[0]\n'
    '                        if target.get("baotou_after") is True:\n'
    '                            piao2_triggered = True\n'
    '                            piao2_target_key = target.get("action_key")\n'
    '                            piao2_hu_score = parent_top_entry.get("score")\n'
    '                            piao2_degrade_reason = "触发"\n'
    '    output_entries = []\n'
    '    for entry in final_entries:\n'
    '        score = entry.get("score")\n'
    '        trace = entry.get("trace")\n'
    '        if piao2_triggered and entry.get("action_key") == piao2_target_key:\n'
    '            new_score = piao2_hu_score + 1.0\n'
    '            piao2_score_delta = new_score - score\n'
    '            score = new_score\n'
    '            trace = {"basis": trace.get("basis"), "base_score": trace.get("base_score"), "shanten_after": trace.get("shanten_after"), "best_shanten_non_pass": trace.get("best_shanten_non_pass"), "wealth_part": trace.get("wealth_part"), "wealth_discard_part": trace.get("wealth_discard_part"), "river_part": trace.get("river_part"), "risk_units": trace.get("risk_units"), "style_part": trace.get("style_part"), "unknown": trace.get("unknown"), "unknown_policy": trace.get("unknown_policy"), "hu_sorting_layer": trace.get("hu_sorting_layer"), "scope": trace.get("scope"), "two_wealth_piao_keeps_baotou_cf": {"version": "two_wealth_piao_keeps_baotou_cf/v1", "triggered": True, "wealth_count": wealth_count, "parent_top_action": piao2_parent_top_action, "hu_score": piao2_hu_score, "score_delta": piao2_score_delta, "degrade_reason": piao2_degrade_reason, "limitation": "仅双财神且唯一hu且唯一财神弃牌且baotou_after为True时的配对反事实改分；其余逐点保持父代"}}\n'
    '        output_entries.append({"action_key": entry.get("action_key"), "score": score, "trace": trace})\n'
    '    reason = "胡以动态排序层优先；未知动作严格锚定在已知最终分最低值以下"\n'
    '    if overlay_triggered:\n'
    '        reason = reason + "；机会边界触发，目标弃牌以胡层上方1分排序"\n'
    '    if dominance_best_key is not None:\n'
    '        reason = reason + "；补杠严格支配判据触发，目标补杠排在胡层上方、已准入飘机会层下方"\n'
    '    if seven_value_triggered:\n'
    '        reason = reason + "；已验证庄家起手域内完整一次自摸条件期望严格胜出时选择七对路线弃牌"\n'
    '    if piao2_triggered:\n'
    '        reason = reason + "；双财神保包头飘反事实触发，目标财神弃牌提到父代hu最终分上方1.0"\n'
    '    else:\n'
    '        reason = reason + "；双财神覆盖未触发（" + piao2_degrade_reason + "），最终entries与父代逐点相同"\n'
    '    return {"status": "SCORED", "entries": output_entries, "reason": reason}\n'
)
